sudo: false
language: cpp

env:
  global:
    - LLVM_VERSION=3.8.0
    - LCOV_ROOT=$HOME/lcov
    - VALGRIND_ROOT=$HOME/valgrind-install

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
    packages: &base_packages
      - python-software-properties
      - libffi-dev
      - libstdc++6
      - binutils-gold
      # Provides a backtrace if the unittests crash
      - gdb

matrix:
  include:
    # gcc coverage
    - compiler: gcc
      env:
        - TOOLSET=gcc
        - COMPILER=g++-6
        - CXXSTD=c++11
        - GCC_VER=6
        - VARIANT=coverage
        - ADDRESS_MODEL=64
        - DO_VALGRIND=false
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
            - lcov
            - libssl-dev
            - *base_packages
          sources:
            - *base_sources

    # older GCC, release
    - compiler: gcc
      env:
        - TOOLSET=gcc
        - COMPILER=g++-4.8
        - CXXSTD=c++11
        - GCC_VER=4.8
        - VARIANT=release
        - DO_VALGRIND=false
        - ADDRESS_MODEL=64
      addons:
        apt:
          packages:
            - gcc-4.8
            - g++-4.8
            - *base_packages
          sources:
            - *base_sources

    # later GCC
    - compiler: gcc
      env:
        - TOOLSET=gcc
        - COMPILER=g++-5
        - CXXSTD=c++11
        - GCC_VER=5
        - VARIANT=release
        - DO_VALGRIND=true
        - ADDRESS_MODEL=64
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
            - libssl-dev
            - valgrind
            - *base_packages
          sources:
            - *base_sources

    # clang ubsan+asan
    - compiler: clang
      env:
        - TOOLSET=clang
        - COMPILER=clang++
        - CXXSTD=c++11
        - GCC_VER=5
        - VARIANT=ubasan
        - CLANG_VER=3.8
        - DO_VALGRIND=false
        - ADDRESS_MODEL=64
        - UBSAN_OPTIONS='print_stacktrace=1'
        - PATH=$PWD/llvm-$LLVM_VERSION/bin:$PATH
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
            - libssl-dev
            - *base_packages
          sources:
            - *base_sources

before_install: &base_before_install
  - scripts/install-dependencies.sh

install:
  - export BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - export BOOST_ROOT="`pwd`"
  - export PATH="`pwd`":$PATH
  - git submodule update --init tools/build
  - git submodule update --init tools/boostdep
  - git submodule update --init libs/asio
  - git submodule update --init libs/assert
  - git submodule update --init libs/config
  - git submodule update --init libs/core
  - git submodule update --init libs/endian
  - git submodule update --init libs/filesystem
  - git submodule update --init libs/intrusive
  - git submodule update --init libs/locale
  - git submodule update --init libs/optional
  - git submodule update --init libs/smart_ptr
  - git submodule update --init libs/static_assert
  - git submodule update --init libs/system
  - git submodule update --init libs/throw_exception
  - git submodule update --init libs/type_traits
  - git submodule update --init libs/utility
  - git submodule update --init libs/winapi

  - git submodule update --init libs/algorithm
  - git submodule update --init libs/array
  - git submodule update --init libs/atomic
  - git submodule update --init libs/bind
  - git submodule update --init libs/chrono
  - git submodule update --init libs/concept_check
  - git submodule update --init libs/container
  - git submodule update --init libs/context
  - git submodule update --init libs/conversion
  - git submodule update --init libs/coroutine
  - git submodule update --init libs/date_time
  - git submodule update --init libs/detail
  - git submodule update --init libs/exception
  - git submodule update --init libs/function
  - git submodule update --init libs/function_types
  - git submodule update --init libs/functional
  - git submodule update --init libs/fusion
  - git submodule update --init libs/integer
  - git submodule update --init libs/io
  - git submodule update --init libs/iterator
  - git submodule update --init libs/lambda
  - git submodule update --init libs/lexical_cast
  - git submodule update --init libs/logic
  - git submodule update --init libs/math
  - git submodule update --init libs/move
  - git submodule update --init libs/mpl
  - git submodule update --init libs/numeric/conversion
  - git submodule update --init libs/pool
  - git submodule update --init libs/predef
  - git submodule update --init libs/preprocessor
  - git submodule update --init libs/random
  - git submodule update --init libs/range
  - git submodule update --init libs/ratio
  - git submodule update --init libs/rational
  - git submodule update --init libs/serialization
  - git submodule update --init libs/thread
  - git submodule update --init libs/tokenizer
  - git submodule update --init libs/tuple
  - git submodule update --init libs/type_index
  - git submodule update --init libs/typeof
  - git submodule update --init libs/unordered
  - rm -rf libs/beast
  - mkdir libs/beast
  - cp -r $TRAVIS_BUILD_DIR/* libs/beast
  - ./bootstrap.sh

script:
  - travis_retry libs/beast/scripts/build-and-test.sh

after_script:
  - cat nohup.out || echo "nohup.out already deleted"

notifications:
  email:
    false
